#ifndef CONFIG_H
#define CONFIG_H

#define CAMERA_SPEED_Y 10
#define CAMERA_SPEED_X 10
#define NOMBRE_PERSONNES 1333
#define NOMBRE_PERSONNES_MAX 20
#define VITESSE_TOP 10
#define VITESSE_BOTTOM 5
#define VITESSE_PERSONNE 4
#define TEMPS_ARRIVE_SECONDE 5400

#endif // CONFIG_H
